import { Leaf, Loader2 } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import type { ProductData } from "@/types/product";
import { RecommendationList } from "@/components/RecommendationList";
import type { ProductRecommendation } from "@/components/RecommendationList";
import { needsRecommendations, buildRecommendationInput, normalizeRecommendation } from "@/lib/utils/productUtils";
import { getRecommendations } from "@/lib/api";

interface LLMRecommendationResponse {
  recommendations?: ProductRecommendation[];
  error?: string;
}

export const RecommendationSection = ({ product }: { product: ProductData }) => {
  const isEnabled = needsRecommendations(product) && Boolean(product.product_name?.trim());

  const { data, isFetching, error } = useQuery<LLMRecommendationResponse, Error>({
    queryKey: ["recommendations", product.product_name, product.brands],
    queryFn: () => getRecommendations(buildRecommendationInput(product)),
    enabled: isEnabled,
    staleTime: 1000 * 60 * 5, // Cache for 5 minutes
    retry: 1,
  });

  if (!needsRecommendations(product)) {
    return null;
  }

  const recommendations = Array.isArray(data?.recommendations)
    ? data.recommendations
        .map((candidate) => normalizeRecommendation(candidate))
        .filter((item): item is ProductRecommendation => Boolean(item))
        .slice(0, 6)
    : [];

  const recommendationMessage = 
    error ? (error.message || "Unable to load alternatives right now.") :
    (data && recommendations.length === 0) ? "The LLM could not infer strong alternatives from the current product data." :
    (!product.product_name?.trim()) ? "No product name available for alternative lookup." : null;

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        <Leaf className="h-5 w-5 text-green-600" />
        <span className="font-semibold text-green-700">LLM Recommended Alternatives</span>
      </div>
      <p className="text-sm text-muted-foreground">
        Alternatives generated by the LLM from the product nutrition and ingredient data.
      </p>
      
      {isFetching ? (
        <div className="rounded-lg border border-border bg-muted/30 p-4 flex items-center gap-3">
          <Loader2 className="h-4 w-4 animate-spin text-primary" />
          <p className="text-sm text-muted-foreground">Generating alternatives...</p>
        </div>
      ) : recommendations.length > 0 ? (
        <RecommendationList
          recommendations={recommendations}
          title="LLM Recommended Alternatives"
          className="border-green-200/30"
        />
      ) : (
        <div className="rounded-lg border border-border bg-muted/30 p-4 text-sm text-muted-foreground">
          {recommendationMessage || "No comparable alternatives found right now."}
        </div>
      )}
    </div>
  );
};
